# SPDX-License-Identifier: MIT
---
_customer_repo_file: >- # noqa: var-naming[no-role-prefix]
  {{
    '/etc/yum.repos.d/linbit.repo'
    if ansible_facts['os_family'] | lower == 'redhat'
    else '/etc/zypp/repos.d/linbit.repo'
    if ansible_facts['os_family'] | lower == 'suse'
    else '/etc/apt/sources.list.d/linbit.list'
  }}
