# SPDX-License-Identifier: MIT
---
# handlers file for customer_repo

# Auto-import LINBIT GPG keys for RHEL family
# kind of hacky, but works - Possible with ansible.builtin.dnf?
- name: Refresh GPG keys (DNF)
  ansible.builtin.command: dnf search bash --assumeyes
  when:
    - ansible_facts['os_family'] | lower == 'redhat'
    - ansible_facts['distribution_major_version'] | int >= 8
  changed_when: true
  failed_when: false
  register: _linbit_dnf_refresh
  until: _linbit_dnf_refresh.rc == 0
  retries: 3
  delay: 10
  listen: refresh_gpg_keys

# Auto-import LINBIT GPG keys for SUSE
- name: Refresh GPG keys (Zypper)
  community.general.zypper:
    name: ""
    # Needed if LINBIT gpg key has not been accepted
    refresh: true
    extra_args_precommand: '--gpg-auto-import-keys --no-gpg-checks'
  when: ansible_facts['os_family'] | lower == 'suse'
  register: _linbit_zypper_refresh
  until: _linbit_zypper_refresh is succeeded
  retries: 3
  delay: 10
  listen: refresh_gpg_keys

- name: Refresh GPG keys (APT)
  ansible.builtin.apt:
    update_cache: true
  when: ansible_facts['os_family'] | lower == 'debian'
  register: _linbit_apt_refresh
  until: _linbit_apt_refresh is succeeded
  retries: 3
  delay: 10
  listen: refresh_gpg_keys
