# SPDX-License-Identifier: MIT
galaxy_info:
  author: LINBIT
  description: Configure LINBIT public package repository for Ubuntu (PPA) and Proxmox VE (APT repo)
  company: LINBIT

  license: MIT

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
        # - resolute
    - name: Debian
      versions:
        - bookworm
        - trixie

  min_ansible_version: '2.9'

  galaxy_tags:
    - linbit
    - proxmox
    - ubuntu
    - ppa
    - apt

dependencies: []
