# SPDX-License-Identifier: MIT
---
- name: Install linbit-keyring package (apt signing key)
  ansible.builtin.apt:
    deb: "{{ public_repo_keyring_package_url }}"
    state: present
    allow_unauthenticated: true
  register: _public_repo_keyring_install
  until: _public_repo_keyring_install is succeeded
  retries: 3

- name: Add LINBIT drbd-9 public Proxmox repo
  ansible.builtin.deb822_repository:
    name: linbit
    types: [deb]
    uris: "{{ public_repo_proxmox_repo }}"
    suites: "proxmox-{{ ansible_facts['distribution_major_version'] | int - 4 }}"
    components: [drbd-9]
    signed_by: "{{ public_repo_gpg_path }}"
  notify: refresh_apt_cache

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
