# SPDX-License-Identifier: MIT
---
- name: Install software-properties-common
  ansible.builtin.apt:
    name: software-properties-common
    state: present

- name: Add LINBIT drbd9-stack PPA
  ansible.builtin.apt_repository:
    repo: "{{ public_repo_ppa }}"
    state: present
  notify: Refresh apt cache

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
