# SPDX-License-Identifier: MIT
---
- name: Fetch PPA signing key fingerprint from Launchpad API
  ansible.builtin.uri:
    url: "{{ public_repo_ppa_api_url }}"
    return_content: true
    method: GET
    headers:
      Accept: "application/json"
  register: _launchpad_response

- name: Add LINBIT drbd9-stack PPA
  ansible.builtin.deb822_repository:
    name: linbit-drbd9-stack
    types: [deb]
    uris: "{{ public_repo_ppa_url }}"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: [main]
    signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x{{ _launchpad_response.json.signing_key_fingerprint }}"
  notify: refresh_apt_cache

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
