# SPDX-License-Identifier: MIT
---
# Ubuntu PPA
public_repo_ppa: 'ppa:linbit/linbit-drbd9-stack'

public_repo_keyring_package_url: 'https://packages.linbit.com/public/linbit-keyring.deb'
public_repo_proxmox_repo: 'http://packages.linbit.com/public/'
public_repo_gpg_path: '/etc/apt/trusted.gpg.d/linbit-keyring.gpg'
