# SPDX-License-Identifier: MIT-0
---
# tasks file for linbit_ppa
- name: Verify host OS is Ubuntu
  ansible.builtin.assert:
    that:
      - "ansible_distribution == 'Ubuntu'"
    msg: "LINBIT PPA only supports Ubuntu"

- name: Install software-properties-common
  ansible.builtin.apt:
    name: software-properties-common
    state: present

- name: Add LINBIT drbd9-stack PPA
  ansible.builtin.apt_repository:
    repo: "{{ lb_ppa }}"
    state: present
  notify: Refresh apt for LINBIT PPA

# Flush now, so software package install tasks have updated indexes
- name: Flush handlers for linbit_ppa
  ansible.builtin.meta: flush_handlers
