# SPDX-License-Identifier: MIT
---
# tasks file for registered_node
- name: Load OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "{{ role_path }}/vars"
      skip: true

- name: Fetch the latest linbit-manage-node.py
  ansible.builtin.get_url:
    url: 'https://my.linbit.com/linbit-manage-node.py'
    dest: '/tmp/linbit-manage-node.py'
    mode: '644'
  retries: 3
  register: registered_node_script_downloaded

- name: Register nodes
  when:
    registered_node_force_register | bool or
    registered_node_script_downloaded.changed
  notify: "{{ registered_node_gpg_handler }}"
  block:
    # Enables all available LINBIT repos available to distro
    - name: Register nodes using linbit-manage-node.py - all repos enabled
      ansible.builtin.shell: |
        bash -c "LB_USERNAME={{ lb_user }} LB_PASSWORD={{ lb_pass }} \
          LB_CONTRACT_ID={{ lb_con_id }} LB_CLUSTER_ID={{ lb_clu_id }} \
          {{ ansible_python.executable }} /tmp/linbit-manage-node.py"
      changed_when: true
      retries: 3
      when:
        - lb_repos is not defined

    # Enables all available LINBIT repos available to distro
    - name: Register nodes using linbit-manage-node.py - selective repos enabled
      ansible.builtin.shell: |
        bash -c "LB_USERNAME={{ lb_user }} LB_PASSWORD={{ lb_pass }} \
          LB_CONTRACT_ID={{ lb_con_id }} LB_CLUSTER_ID={{ lb_clu_id }} \
          LB_REPOS={{ lb_repos }} {{ ansible_python.executable }} /tmp/linbit-manage-node.py"
      changed_when: true
      retries: 3
      when:
        - lb_repos is defined
        - lb_repos | length > 0
  rescue:
    - name: Remove registered node script on failure to register nodes
      ansible.builtin.file:
        path: /tmp/linbit-manage-node.py
        state: absent

    - name: End play if nodes fail to register
      ansible.builtin.fail:
        msg: "Failed to register nodes, aborting playbook."

- name: Use specific RHEL version for DRBD repos
  ansible.builtin.include_tasks:
    redhat_minor_repo.yml
  when:
    - registered_node_use_rhel_minor_version is defined
    - registered_node_use_rhel_minor_version | bool
    - ansible_distribution | lower == 'redhat'

### FOR STAGING
- name: Configure LINBIT staging repository using regex
  ansible.builtin.lineinfile:
    path: "{{ repo_file }}"
    regexp: '(https\://packages\.linbit\.com/[a-zA-Z0-9]+/)'
    line: '\1staging/'
    backrefs: true
  when:
    - staging is defined
    - staging | bool

# Force GPG key and package manager cache refreshes
- name: Flush handlers for registered_node
  ansible.builtin.meta: flush_handlers
