# SPDX-License-Identifier: MIT
---
- name: Check if LINBIT GPG keyring is installed
  ansible.builtin.command: rpm -q linbit-keyring
  register: _linbit_keyring_check
  changed_when: false
  failed_when: false

- name: Install LINBIT GPG keyring
  community.general.zypper:
    name: https://packages.linbit.com/public/linbit-keyring.rpm
    state: present
    disable_gpg_check: true
  when: _linbit_keyring_check.rc != 0
