# SPDX-License-Identifier: MIT
---
- name: Install LINBIT GPG keyring
  community.general.zypper:
    name: "https://packages.linbit.com/public/linbit-keyring/{{ _linbit_distribution }}/linbit-keyring.rpm"
    state: latest
    disable_gpg_check: true

- name: Import LINBIT GPG keys into RPM database
  ansible.builtin.command: rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-linbit
  register: _rpm_import
  changed_when: _rpm_import.rc == 0
