# SPDX-License-Identifier: MIT
---
- name: Install LINBIT GPG keyring (DNF)
  ansible.builtin.dnf:
    name: "https://packages.linbit.com/public/linbit-keyring/{{ _linbit_distribution }}/linbit-keyring.rpm"
    state: latest
    disable_gpg_check: true

- name: Check if LINBIT GPG key is already imported
  ansible.builtin.shell:
    cmd: rpm -q gpg-pubkey --qf '%{SUMMARY}\n' | grep -qi linbit
  register: _linbit_key_check
  changed_when: false
  failed_when: false

- name: Import LINBIT GPG keys into RPM database
  ansible.builtin.command: rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-linbit
  when: _linbit_key_check.rc != 0
